image: Visual Studio 2019

environment:
  IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1

install:
  - ps: gitversion /l console /output buildserver

configuration:
  - Release

dotnet_csproj:
  patch: true
  version: '$(GitVersion_SemVer)'

build_script:
- cmd: >-
    dotnet build

    dotnet pack

    7z a reportportal-%GitVersion_SemVer%-net462.zip ./src/ReportPortal.XUnitReporter/bin/%configuration%/net462/ReportPortal*

    7z a reportportal-%GitVersion_SemVer%-netcoreapp3.1.zip ./src/ReportPortal.XUnitReporter/bin/%configuration%/netcoreapp3.1/ReportPortal*

test: off

artifacts:
  - path: '**\*.zip'
  - path: '**\*.nupkg'